### PR TITLE
Allow Merged Group Variables

### PR DESCRIPTION
**Pull request by p-rintz**
As discussed in issue #11 .

This enables support for multiple group variables that are imported from the Ansible groups the specific server is part of.

This also adds Centos Support and fixes a few typos and warnings. I dont know if you would like this to be a second pull request or not.

Id be happy to change things if you have any ideas/suggestions.

### CODE REVIEW

**Comment by p-rintz** [comment]
I pushed a fix for when a group variable file for nftables did not exist.

It failed before since It tried loading files that didnt exist.

**Comment by vrga** [comment]
May I reccommend this as an alternative to hardcoding some merging in this project? 
https://github.com/leapfrogonline/ansible-merge-vars

I've used this for a significant amount of time in my private ansible playbooks to great effect :)

**Comment by gardouille** [comment]
Looking the PR, thanks @p-rintz !

@vrga I like the idea of a self-sufficient role.
ansible-merge-vars looks nice but require at least some vars renaming… I keep it in mind and will look if it's possible to integrate it in a role.

**Comment by gardouille** [comment]
:+1: for merged_groups_dir variable.

I think it might be a good idea to keep debug with a `nft__debug` var. Can you add it (default to False).

Also, can you prefix merged_groups* vars with `nft__` please ? I find it easier to know the related module :)

**Comment by gardouille** [comment]
I forgot `nftable_` -> `nftables_` vars.

And the actual behaviour suppose to work with vars/groupname as a file. But "many" others organization can be used ([organizing host and group variables](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#organizing-host-and-group-variables)).

In my case i have the last behaviour… ^^
```
├── group_vars
│   ├── all
│   │   ├── …
│   │   ├── nftables.yml
│   ├── xxx
│   │   ├── …
│   │   ├── nftables.yml
│   ├── nfs
│   │   ├── nftables.yml
```

If you have any idea to make it work (trying some stuff on my own).

**Comment by p-rintz** [comment]
I specifically tried to keep the variable files out of default Ansible folders, so that they arent imported by other means.
the vars folder is just the default that I kept and also why its possible to change the folder where the nftables rules should be imported from. 

The way you want to structure the nftables rules is of course possible. (other than the "all" file, because by default the all group is not part of the "group_names" ansible variable.)
Since I already test the existence of the files, I could also test for the existence of nftables.yml files inside group folders. Ill have to think about potential side-effects with doing that. 

The debug variable was something I forgot while cleaning up. I can of course keep it and include a debug toggle.

**Comment by gardouille** [comment]
Keep this behaviour, i will re-read, re-test and probably edit my configuration :)

The debug can be useful for non expert (like me… even if i misunderstood the whole thing :D).

**Comment by p-rintz** [comment]
I added the debug toggle as requested and also added a second debug message to output the merged group rules.
If/When you want to add additional debug messages at other places (I thought it would be better for you to decide where to do this), simply add them with the "nft_debug" boolean:

```
- debug: var=nft_combined_rules
  when: nft_debug
```

I also replaced the variable names as you requested.

**Comment by p-rintz** [comment]
Also look at the defaults/main.yml formatting please. The comments look very much like the formatting is part of some standard, but none that I know, so I simply tried to adhere to it, but I dont know/couldnt test if I maybe had a space too much somewhere or the like and broke the standard formatting it is supposed to have.

**Comment by gardouille** [comment]
Don't worry, you can't broke anything as i have not really use it from now ^^ It's mostly inspired from [DebOps](https://github.com/debops/debops) formatting but i still didn't put any automation (it wasn't really supposed to have more than 1 user of my role when i started it :D).

Everything looks good, many thanks !

Merging today.

**Pull request merged**
