### PR TITLE
Wip enable service from tasks

### PR DESCRIPTION
**Pull request by mjourdan**
This aims to solve #34.

### CODE REVIEW

**Comment by kravietz** [comment]
Need to make sure this is prominently documented, but otherwise looks good.

**Comment by mjourdan** [comment]
> Need to make sure this is prominently documented, but otherwise looks good.

Thanks for the review. I added a bit of documentation and also added asynchronous polling to fix #35.

**Comment by stejoo** [comment]
I like this.
But you do seem to have based this work on top of your other PR that add the disable firewalld functionality. Might I suggest you separate those changes? You could rebase this branch onto `master` and leave out commits `7827889` and `ed4cd83`.

**Comment by mjourdan** [comment]
Good idea @stejoo, I did as you suggested.

**Comment by stejoo** [comment]
Nice, this looks cleaner. Hope somebody can take a look at it. Ensuring the service is activated is an important of defining the desired state.

**Pull request merged**
