### PR TITLE
Sigstore releases

### PR DESCRIPTION
**Pull request by kravietz**
New GitHub Actions:
* Use a new Molecule action for commits (cosmetic)
* Use new SigStore framework to sign releases
* Upload new releases to Ansible Galaxy automatically

### CODE REVIEW

**Comment by kravietz** [comment]
@gardouille With this MR, if you just defined `ANSIBLE_GALAXY_TOKEN` in repository Settings > Secrets (the token can be retrieved from galaxy.ansible.com profile), new tag will trigger new release on GitHub, signed by SigStore and then automatically import the release into Galaxy.

**Comment by gardouille** [comment]
I defined the secret and we can test this with the new v2.2.0 release. Thank you !

**Comment by gardouille** [comment]
Hmmm, an error occured during "Sign release with Sigstore".
https://github.com/ipr-cnrs/nftables/actions/runs/3386592855/jobs/5626190704

I tag the release with my account this time, but the commit is verified, so not sure where the error might be… Any clue @kravietz ? Should i retry with the previous account ?

**Comment by kravietz** [comment]
@gardouille This seems to be just an internal error of `sigstore`, possibly due to the server being unavailable at the time or something like that. I have worked around this by adding `continue-on-error: true` to the SigStore related tasks, so they will be just skipped in case of error but won't break the release.

https://github.com/ipr-cnrs/nftables/blob/master/.github/workflows/release.yaml#L42

**Pull request merged**
